^0::{
   SendText "2410278"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "50"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2244858"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "30"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2244860"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "50"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "0353589"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "19042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "30"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "1699787"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "19042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "30"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2410266"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "19042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "50"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2967741"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "07052024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   Return
}

^1::{
   SendText "2629677"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "50"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2629665"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "21042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "3001829"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "21042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   Return
}

^2::{
   SendText "2411349"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "50"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "3090450"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "30"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2411350"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "19042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "50"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2596635"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "21042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2244895"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "22042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "3147654"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "22042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "3115422"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "23042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "1666186"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "25042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2877200"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "25042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "50"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500

   Return
}

^3::{
   SendText "2318246"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "20042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "30"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2429020"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "30"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2534046"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "30"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "3089976"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "19042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "3090413"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "21042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "30"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "0432416"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "23042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2088484"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "23042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "3130009"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "23042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2088502"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "24042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2241286"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "25042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "0537196"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "28042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "0501980"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "21042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "50"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500

   Return
}

^4::{
   SendText "0313294"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "19042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "30"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2493275"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "23042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2523670"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "23042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "1666186"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "25042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2926581"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "25042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "30"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "3089976"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "26042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2366368"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "02052024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "2934619"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "17052024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "3103924"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "17052024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "20"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500

   Return
}
^5::{
   SendText "1669734"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Tab Down}"
   Send "{Tab Up}"
   Send "{Tab Down}"
   Send "{Tab Up}"
   SendText "18042024"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500
   SendText "50"
   Send "{Enter Down}"
   Send "{Enter Up}"
   Sleep 500

   Return
}
^6::{

   Return
}
^7::{

   Return
}
^8::{

   Return
}
^9::{

   Return
}
^j::{

   Return
}

